version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/openjdk:18.0
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Dwanford/sf-pet-clinic/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  maven-install:

    executor: main-executor
    steps:
      - checkout
      - run: |
          mvn install

  tests:

    executor: main-executor
    steps:
      - run: |
          mvn integration-test

workflows:
  tests-workflow:
    jobs:
      - maven-install
      - tests
