version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/openjdk:18-jdk
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Dwanford/sf-pet-clinic/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  tests:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          mvn install

workflows:
  tests-workflow:
    jobs:
      - tests
